# Generated by Django 5.2.3 on 2025-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingwebhook",
            name="type_request",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
